// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

#ifndef PROTOBUF_user_2eproto__INCLUDED
#define PROTOBUF_user_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace server2N {
class CONECT_STATUS;
class CONECT_STATUSDefaultTypeInternal;
extern CONECT_STATUSDefaultTypeInternal _CONECT_STATUS_default_instance_;
class User;
class UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
class User_Action;
class User_ActionDefaultTypeInternal;
extern User_ActionDefaultTypeInternal _User_Action_default_instance_;
}  // namespace server2N

namespace server2N {

namespace protobuf_user_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_user_2eproto

enum User_Action_ACTION_TYPE {
  User_Action_ACTION_TYPE_MOVE = 0,
  User_Action_ACTION_TYPE_JUMP = 1,
  User_Action_ACTION_TYPE_User_Action_ACTION_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  User_Action_ACTION_TYPE_User_Action_ACTION_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool User_Action_ACTION_TYPE_IsValid(int value);
const User_Action_ACTION_TYPE User_Action_ACTION_TYPE_ACTION_TYPE_MIN = User_Action_ACTION_TYPE_MOVE;
const User_Action_ACTION_TYPE User_Action_ACTION_TYPE_ACTION_TYPE_MAX = User_Action_ACTION_TYPE_JUMP;
const int User_Action_ACTION_TYPE_ACTION_TYPE_ARRAYSIZE = User_Action_ACTION_TYPE_ACTION_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* User_Action_ACTION_TYPE_descriptor();
inline const ::std::string& User_Action_ACTION_TYPE_Name(User_Action_ACTION_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    User_Action_ACTION_TYPE_descriptor(), value);
}
inline bool User_Action_ACTION_TYPE_Parse(
    const ::std::string& name, User_Action_ACTION_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<User_Action_ACTION_TYPE>(
    User_Action_ACTION_TYPE_descriptor(), name, value);
}
enum User_SEND_TYPE {
  User_SEND_TYPE_INTERPOLATION = 0,
  User_SEND_TYPE_EVENT_SEND = 1,
  User_SEND_TYPE_User_SEND_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  User_SEND_TYPE_User_SEND_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool User_SEND_TYPE_IsValid(int value);
const User_SEND_TYPE User_SEND_TYPE_SEND_TYPE_MIN = User_SEND_TYPE_INTERPOLATION;
const User_SEND_TYPE User_SEND_TYPE_SEND_TYPE_MAX = User_SEND_TYPE_EVENT_SEND;
const int User_SEND_TYPE_SEND_TYPE_ARRAYSIZE = User_SEND_TYPE_SEND_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* User_SEND_TYPE_descriptor();
inline const ::std::string& User_SEND_TYPE_Name(User_SEND_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    User_SEND_TYPE_descriptor(), value);
}
inline bool User_SEND_TYPE_Parse(
    const ::std::string& name, User_SEND_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<User_SEND_TYPE>(
    User_SEND_TYPE_descriptor(), name, value);
}
enum CONECT_STATUS_CONNECT_STATUS {
  CONECT_STATUS_CONNECT_STATUS_FAIL = 0,
  CONECT_STATUS_CONNECT_STATUS_REQUEST = 98,
  CONECT_STATUS_CONNECT_STATUS_RESPONSE = 99,
  CONECT_STATUS_CONNECT_STATUS_CONNECT = 100,
  CONECT_STATUS_CONNECT_STATUS_DISCONNECT = 101,
  CONECT_STATUS_CONNECT_STATUS_CONECT_STATUS_CONNECT_STATUS_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  CONECT_STATUS_CONNECT_STATUS_CONECT_STATUS_CONNECT_STATUS_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool CONECT_STATUS_CONNECT_STATUS_IsValid(int value);
const CONECT_STATUS_CONNECT_STATUS CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_MIN = CONECT_STATUS_CONNECT_STATUS_FAIL;
const CONECT_STATUS_CONNECT_STATUS CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_MAX = CONECT_STATUS_CONNECT_STATUS_DISCONNECT;
const int CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_ARRAYSIZE = CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_MAX + 1;

const ::google::protobuf::EnumDescriptor* CONECT_STATUS_CONNECT_STATUS_descriptor();
inline const ::std::string& CONECT_STATUS_CONNECT_STATUS_Name(CONECT_STATUS_CONNECT_STATUS value) {
  return ::google::protobuf::internal::NameOfEnum(
    CONECT_STATUS_CONNECT_STATUS_descriptor(), value);
}
inline bool CONECT_STATUS_CONNECT_STATUS_Parse(
    const ::std::string& name, CONECT_STATUS_CONNECT_STATUS* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CONECT_STATUS_CONNECT_STATUS>(
    CONECT_STATUS_CONNECT_STATUS_descriptor(), name, value);
}
// ===================================================================

class User_Action : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server2N.User.Action) */ {
 public:
  User_Action();
  virtual ~User_Action();

  User_Action(const User_Action& from);

  inline User_Action& operator=(const User_Action& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const User_Action& default_instance();

  static inline const User_Action* internal_default_instance() {
    return reinterpret_cast<const User_Action*>(
               &_User_Action_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(User_Action* other);

  // implements Message ----------------------------------------------

  inline User_Action* New() const PROTOBUF_FINAL { return New(NULL); }

  User_Action* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const User_Action& from);
  void MergeFrom(const User_Action& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(User_Action* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef User_Action_ACTION_TYPE ACTION_TYPE;
  static const ACTION_TYPE MOVE =
    User_Action_ACTION_TYPE_MOVE;
  static const ACTION_TYPE JUMP =
    User_Action_ACTION_TYPE_JUMP;
  static inline bool ACTION_TYPE_IsValid(int value) {
    return User_Action_ACTION_TYPE_IsValid(value);
  }
  static const ACTION_TYPE ACTION_TYPE_MIN =
    User_Action_ACTION_TYPE_ACTION_TYPE_MIN;
  static const ACTION_TYPE ACTION_TYPE_MAX =
    User_Action_ACTION_TYPE_ACTION_TYPE_MAX;
  static const int ACTION_TYPE_ARRAYSIZE =
    User_Action_ACTION_TYPE_ACTION_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ACTION_TYPE_descriptor() {
    return User_Action_ACTION_TYPE_descriptor();
  }
  static inline const ::std::string& ACTION_TYPE_Name(ACTION_TYPE value) {
    return User_Action_ACTION_TYPE_Name(value);
  }
  static inline bool ACTION_TYPE_Parse(const ::std::string& name,
      ACTION_TYPE* value) {
    return User_Action_ACTION_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 posX = 3;
  void clear_posx();
  static const int kPosXFieldNumber = 3;
  ::google::protobuf::int32 posx() const;
  void set_posx(::google::protobuf::int32 value);

  // int32 posY = 4;
  void clear_posy();
  static const int kPosYFieldNumber = 4;
  ::google::protobuf::int32 posy() const;
  void set_posy(::google::protobuf::int32 value);

  // int32 speed = 5;
  void clear_speed();
  static const int kSpeedFieldNumber = 5;
  ::google::protobuf::int32 speed() const;
  void set_speed(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:server2N.User.Action)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 posx_;
  ::google::protobuf::int32 posy_;
  ::google::protobuf::int32 speed_;
  mutable int _cached_size_;
  friend struct protobuf_user_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class User : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server2N.User) */ {
 public:
  User();
  virtual ~User();

  User(const User& from);

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const User& default_instance();

  static inline const User* internal_default_instance() {
    return reinterpret_cast<const User*>(
               &_User_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(User* other);

  // implements Message ----------------------------------------------

  inline User* New() const PROTOBUF_FINAL { return New(NULL); }

  User* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const User& from);
  void MergeFrom(const User& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(User* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef User_Action Action;

  typedef User_SEND_TYPE SEND_TYPE;
  static const SEND_TYPE INTERPOLATION =
    User_SEND_TYPE_INTERPOLATION;
  static const SEND_TYPE EVENT_SEND =
    User_SEND_TYPE_EVENT_SEND;
  static inline bool SEND_TYPE_IsValid(int value) {
    return User_SEND_TYPE_IsValid(value);
  }
  static const SEND_TYPE SEND_TYPE_MIN =
    User_SEND_TYPE_SEND_TYPE_MIN;
  static const SEND_TYPE SEND_TYPE_MAX =
    User_SEND_TYPE_SEND_TYPE_MAX;
  static const int SEND_TYPE_ARRAYSIZE =
    User_SEND_TYPE_SEND_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  SEND_TYPE_descriptor() {
    return User_SEND_TYPE_descriptor();
  }
  static inline const ::std::string& SEND_TYPE_Name(SEND_TYPE value) {
    return User_SEND_TYPE_Name(value);
  }
  static inline bool SEND_TYPE_Parse(const ::std::string& name,
      SEND_TYPE* value) {
    return User_SEND_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:server2N.User)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 id_;
  mutable int _cached_size_;
  friend struct protobuf_user_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CONECT_STATUS : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server2N.CONECT_STATUS) */ {
 public:
  CONECT_STATUS();
  virtual ~CONECT_STATUS();

  CONECT_STATUS(const CONECT_STATUS& from);

  inline CONECT_STATUS& operator=(const CONECT_STATUS& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CONECT_STATUS& default_instance();

  static inline const CONECT_STATUS* internal_default_instance() {
    return reinterpret_cast<const CONECT_STATUS*>(
               &_CONECT_STATUS_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(CONECT_STATUS* other);

  // implements Message ----------------------------------------------

  inline CONECT_STATUS* New() const PROTOBUF_FINAL { return New(NULL); }

  CONECT_STATUS* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CONECT_STATUS& from);
  void MergeFrom(const CONECT_STATUS& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CONECT_STATUS* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef CONECT_STATUS_CONNECT_STATUS CONNECT_STATUS;
  static const CONNECT_STATUS FAIL =
    CONECT_STATUS_CONNECT_STATUS_FAIL;
  static const CONNECT_STATUS REQUEST =
    CONECT_STATUS_CONNECT_STATUS_REQUEST;
  static const CONNECT_STATUS RESPONSE =
    CONECT_STATUS_CONNECT_STATUS_RESPONSE;
  static const CONNECT_STATUS CONNECT =
    CONECT_STATUS_CONNECT_STATUS_CONNECT;
  static const CONNECT_STATUS DISCONNECT =
    CONECT_STATUS_CONNECT_STATUS_DISCONNECT;
  static inline bool CONNECT_STATUS_IsValid(int value) {
    return CONECT_STATUS_CONNECT_STATUS_IsValid(value);
  }
  static const CONNECT_STATUS CONNECT_STATUS_MIN =
    CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_MIN;
  static const CONNECT_STATUS CONNECT_STATUS_MAX =
    CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_MAX;
  static const int CONNECT_STATUS_ARRAYSIZE =
    CONECT_STATUS_CONNECT_STATUS_CONNECT_STATUS_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CONNECT_STATUS_descriptor() {
    return CONECT_STATUS_CONNECT_STATUS_descriptor();
  }
  static inline const ::std::string& CONNECT_STATUS_Name(CONNECT_STATUS value) {
    return CONECT_STATUS_CONNECT_STATUS_Name(value);
  }
  static inline bool CONNECT_STATUS_Parse(const ::std::string& name,
      CONNECT_STATUS* value) {
    return CONECT_STATUS_CONNECT_STATUS_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:server2N.CONECT_STATUS)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 type_;
  mutable int _cached_size_;
  friend struct protobuf_user_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// User_Action

// int32 type = 2;
inline void User_Action::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 User_Action::type() const {
  // @@protoc_insertion_point(field_get:server2N.User.Action.type)
  return type_;
}
inline void User_Action::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:server2N.User.Action.type)
}

// int32 posX = 3;
inline void User_Action::clear_posx() {
  posx_ = 0;
}
inline ::google::protobuf::int32 User_Action::posx() const {
  // @@protoc_insertion_point(field_get:server2N.User.Action.posX)
  return posx_;
}
inline void User_Action::set_posx(::google::protobuf::int32 value) {
  
  posx_ = value;
  // @@protoc_insertion_point(field_set:server2N.User.Action.posX)
}

// int32 posY = 4;
inline void User_Action::clear_posy() {
  posy_ = 0;
}
inline ::google::protobuf::int32 User_Action::posy() const {
  // @@protoc_insertion_point(field_get:server2N.User.Action.posY)
  return posy_;
}
inline void User_Action::set_posy(::google::protobuf::int32 value) {
  
  posy_ = value;
  // @@protoc_insertion_point(field_set:server2N.User.Action.posY)
}

// int32 speed = 5;
inline void User_Action::clear_speed() {
  speed_ = 0;
}
inline ::google::protobuf::int32 User_Action::speed() const {
  // @@protoc_insertion_point(field_get:server2N.User.Action.speed)
  return speed_;
}
inline void User_Action::set_speed(::google::protobuf::int32 value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:server2N.User.Action.speed)
}

// -------------------------------------------------------------------

// User

// int32 id = 1;
inline void User::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 User::id() const {
  // @@protoc_insertion_point(field_get:server2N.User.id)
  return id_;
}
inline void User::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:server2N.User.id)
}

// -------------------------------------------------------------------

// CONECT_STATUS

// int32 id = 1;
inline void CONECT_STATUS::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 CONECT_STATUS::id() const {
  // @@protoc_insertion_point(field_get:server2N.CONECT_STATUS.id)
  return id_;
}
inline void CONECT_STATUS::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:server2N.CONECT_STATUS.id)
}

// int32 type = 2;
inline void CONECT_STATUS::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 CONECT_STATUS::type() const {
  // @@protoc_insertion_point(field_get:server2N.CONECT_STATUS.type)
  return type_;
}
inline void CONECT_STATUS::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:server2N.CONECT_STATUS.type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace server2N

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::server2N::User_Action_ACTION_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::server2N::User_Action_ACTION_TYPE>() {
  return ::server2N::User_Action_ACTION_TYPE_descriptor();
}
template <> struct is_proto_enum< ::server2N::User_SEND_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::server2N::User_SEND_TYPE>() {
  return ::server2N::User_SEND_TYPE_descriptor();
}
template <> struct is_proto_enum< ::server2N::CONECT_STATUS_CONNECT_STATUS> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::server2N::CONECT_STATUS_CONNECT_STATUS>() {
  return ::server2N::CONECT_STATUS_CONNECT_STATUS_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_user_2eproto__INCLUDED
