// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameContent.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Server2N {

  /// <summary>Holder for reflection information generated from gameContent.proto</summary>
  public static partial class GameContentReflection {

    #region Descriptor
    /// <summary>File descriptor for gameContent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameContentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFnYW1lQ29udGVudC5wcm90bxIIc2VydmVyMk4ipwEKDEdsb2JhbE5vdGlj",
            "ZRIvCgRub3RpGAEgASgOMiEuc2VydmVyMk4uR2xvYmFsTm90aWNlLk5vdGlj",
            "ZUluZm8SDgoGbm90aWNlGAIgASgJEhEKCXBlcmZvcm1lchgDIAEoBRIOCgZ2",
            "aWN0aW0YBCADKAUiMwoKTm90aWNlSW5mbxILCgdOb3RoaW5nEAASDAoIS2ls",
            "bEluZm8QARIKCgZOb3RpY2UQAiL1AQoOVXNlckNvbm5lY3Rpb24SEwoLY29u",
            "bmVjdG9ySWQYASADKAUSEAoIa2lsbEluZm8YAiADKAUSEQoJZGVhdGhJbmZv",
            "GAMgAygFEhAKCG5pY2tuYW1lGAQgAygJEjgKB2NvblR5cGUYBSABKA4yJy5z",
            "ZXJ2ZXIyTi5Vc2VyQ29ubmVjdGlvbi5Db25uZWN0aW9uVHlwZSJdCg5Db25u",
            "ZWN0aW9uVHlwZRILCgdOb3RoaW5nEAASCwoHQ29ubmVjdBABEg4KClRyeUNv",
            "bm5lY3QQAhIRCg1BY2NlcHRDb25uZWN0EAMSDgoKRGlzQ29ubmVjdBAEIpoC",
            "CglHYW1lRXZlbnQSJwoDYWN0GAEgASgOMhouc2VydmVyMk4uR2FtZUV2ZW50",
            "LmFjdGlvbhIWCg5hY3Rpb25Qcm9wZXJ0eRgFIAEoBRIWCg5FdmVudFBvc2l0",
            "aW9uWBgGIAEoAhIWCg5FdmVudFBvc2l0aW9uWRgHIAEoAhIRCglWZWxvY2l0",
            "eVgYCCABKAISEQoJVmVsb2NpdHlZGAkgASgCEhEKCWludm9rZXJJZBgKIAMo",
            "BSJjCgZhY3Rpb24SCwoHTm90aGluZxAAEggKBE1vdmUQZBIICgRTdG9wEGUS",
            "CAoESnVtcBBmEgkKBVNob290EGcSCgoGR2V0SGl0EGgSCQoFU3Bhd24QaRIM",
            "CghVc2VyU3luYxBqIpACCgpQYWNrZXRCb2R5EjIKB21zZ1R5cGUYkE4gASgO",
            "MiAuc2VydmVyMk4uUGFja2V0Qm9keS5tZXNzYWdlVHlwZRIpCgdjb25uZWN0",
            "GAYgASgLMhguc2VydmVyMk4uVXNlckNvbm5lY3Rpb24SJwoGbm90aWNlGJFO",
            "IAEoCzIWLnNlcnZlcjJOLkdsb2JhbE5vdGljZRIiCgVldmVudBgHIAEoCzIT",
            "LnNlcnZlcjJOLkdhbWVFdmVudBIQCghzZW5kZXJJZBgIIAEoBSJECgttZXNz",
            "YWdlVHlwZRINCglHYW1lRXZlbnQQABITCg5Vc2VyQ29ubmVjdGlvbhCQThIR",
            "CgxHbG9iYWxOb3RpY2UQkU5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Server2N.GlobalNotice), global::Server2N.GlobalNotice.Parser, new[]{ "Noti", "Notice", "Performer", "Victim" }, null, new[]{ typeof(global::Server2N.GlobalNotice.Types.NoticeInfo) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server2N.UserConnection), global::Server2N.UserConnection.Parser, new[]{ "ConnectorId", "KillInfo", "DeathInfo", "Nickname", "ConType" }, null, new[]{ typeof(global::Server2N.UserConnection.Types.ConnectionType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server2N.GameEvent), global::Server2N.GameEvent.Parser, new[]{ "Act", "ActionProperty", "EventPositionX", "EventPositionY", "VelocityX", "VelocityY", "InvokerId" }, null, new[]{ typeof(global::Server2N.GameEvent.Types.action) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Server2N.PacketBody), global::Server2N.PacketBody.Parser, new[]{ "MsgType", "Connect", "Notice", "Event", "SenderId" }, null, new[]{ typeof(global::Server2N.PacketBody.Types.messageType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GlobalNotice : pb::IMessage<GlobalNotice> {
    private static readonly pb::MessageParser<GlobalNotice> _parser = new pb::MessageParser<GlobalNotice>(() => new GlobalNotice());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GlobalNotice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server2N.GameContentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalNotice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalNotice(GlobalNotice other) : this() {
      noti_ = other.noti_;
      notice_ = other.notice_;
      performer_ = other.performer_;
      victim_ = other.victim_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalNotice Clone() {
      return new GlobalNotice(this);
    }

    /// <summary>Field number for the "noti" field.</summary>
    public const int NotiFieldNumber = 1;
    private global::Server2N.GlobalNotice.Types.NoticeInfo noti_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.GlobalNotice.Types.NoticeInfo Noti {
      get { return noti_; }
      set {
        noti_ = value;
      }
    }

    /// <summary>Field number for the "notice" field.</summary>
    public const int NoticeFieldNumber = 2;
    private string notice_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Notice {
      get { return notice_; }
      set {
        notice_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "performer" field.</summary>
    public const int PerformerFieldNumber = 3;
    private int performer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Performer {
      get { return performer_; }
      set {
        performer_ = value;
      }
    }

    /// <summary>Field number for the "victim" field.</summary>
    public const int VictimFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_victim_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> victim_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Victim {
      get { return victim_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GlobalNotice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GlobalNotice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Noti != other.Noti) return false;
      if (Notice != other.Notice) return false;
      if (Performer != other.Performer) return false;
      if(!victim_.Equals(other.victim_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Noti != 0) hash ^= Noti.GetHashCode();
      if (Notice.Length != 0) hash ^= Notice.GetHashCode();
      if (Performer != 0) hash ^= Performer.GetHashCode();
      hash ^= victim_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Noti != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Noti);
      }
      if (Notice.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Notice);
      }
      if (Performer != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Performer);
      }
      victim_.WriteTo(output, _repeated_victim_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Noti != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Noti);
      }
      if (Notice.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Notice);
      }
      if (Performer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Performer);
      }
      size += victim_.CalculateSize(_repeated_victim_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GlobalNotice other) {
      if (other == null) {
        return;
      }
      if (other.Noti != 0) {
        Noti = other.Noti;
      }
      if (other.Notice.Length != 0) {
        Notice = other.Notice;
      }
      if (other.Performer != 0) {
        Performer = other.Performer;
      }
      victim_.Add(other.victim_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            noti_ = (global::Server2N.GlobalNotice.Types.NoticeInfo) input.ReadEnum();
            break;
          }
          case 18: {
            Notice = input.ReadString();
            break;
          }
          case 24: {
            Performer = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            victim_.AddEntriesFrom(input, _repeated_victim_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GlobalNotice message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum NoticeInfo {
        [pbr::OriginalName("Nothing")] Nothing = 0,
        [pbr::OriginalName("KillInfo")] KillInfo = 1,
        [pbr::OriginalName("Notice")] Notice = 2,
      }

    }
    #endregion

  }

  public sealed partial class UserConnection : pb::IMessage<UserConnection> {
    private static readonly pb::MessageParser<UserConnection> _parser = new pb::MessageParser<UserConnection>(() => new UserConnection());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserConnection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server2N.GameContentReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserConnection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserConnection(UserConnection other) : this() {
      connectorId_ = other.connectorId_.Clone();
      killInfo_ = other.killInfo_.Clone();
      deathInfo_ = other.deathInfo_.Clone();
      nickname_ = other.nickname_.Clone();
      conType_ = other.conType_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserConnection Clone() {
      return new UserConnection(this);
    }

    /// <summary>Field number for the "connectorId" field.</summary>
    public const int ConnectorIdFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_connectorId_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> connectorId_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> ConnectorId {
      get { return connectorId_; }
    }

    /// <summary>Field number for the "killInfo" field.</summary>
    public const int KillInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_killInfo_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> killInfo_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> KillInfo {
      get { return killInfo_; }
    }

    /// <summary>Field number for the "deathInfo" field.</summary>
    public const int DeathInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_deathInfo_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> deathInfo_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> DeathInfo {
      get { return deathInfo_; }
    }

    /// <summary>Field number for the "nickname" field.</summary>
    public const int NicknameFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_nickname_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> nickname_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Nickname {
      get { return nickname_; }
    }

    /// <summary>Field number for the "conType" field.</summary>
    public const int ConTypeFieldNumber = 5;
    private global::Server2N.UserConnection.Types.ConnectionType conType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.UserConnection.Types.ConnectionType ConType {
      get { return conType_; }
      set {
        conType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserConnection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserConnection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!connectorId_.Equals(other.connectorId_)) return false;
      if(!killInfo_.Equals(other.killInfo_)) return false;
      if(!deathInfo_.Equals(other.deathInfo_)) return false;
      if(!nickname_.Equals(other.nickname_)) return false;
      if (ConType != other.ConType) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= connectorId_.GetHashCode();
      hash ^= killInfo_.GetHashCode();
      hash ^= deathInfo_.GetHashCode();
      hash ^= nickname_.GetHashCode();
      if (ConType != 0) hash ^= ConType.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      connectorId_.WriteTo(output, _repeated_connectorId_codec);
      killInfo_.WriteTo(output, _repeated_killInfo_codec);
      deathInfo_.WriteTo(output, _repeated_deathInfo_codec);
      nickname_.WriteTo(output, _repeated_nickname_codec);
      if (ConType != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ConType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += connectorId_.CalculateSize(_repeated_connectorId_codec);
      size += killInfo_.CalculateSize(_repeated_killInfo_codec);
      size += deathInfo_.CalculateSize(_repeated_deathInfo_codec);
      size += nickname_.CalculateSize(_repeated_nickname_codec);
      if (ConType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ConType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserConnection other) {
      if (other == null) {
        return;
      }
      connectorId_.Add(other.connectorId_);
      killInfo_.Add(other.killInfo_);
      deathInfo_.Add(other.deathInfo_);
      nickname_.Add(other.nickname_);
      if (other.ConType != 0) {
        ConType = other.ConType;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10:
          case 8: {
            connectorId_.AddEntriesFrom(input, _repeated_connectorId_codec);
            break;
          }
          case 18:
          case 16: {
            killInfo_.AddEntriesFrom(input, _repeated_killInfo_codec);
            break;
          }
          case 26:
          case 24: {
            deathInfo_.AddEntriesFrom(input, _repeated_deathInfo_codec);
            break;
          }
          case 34: {
            nickname_.AddEntriesFrom(input, _repeated_nickname_codec);
            break;
          }
          case 40: {
            conType_ = (global::Server2N.UserConnection.Types.ConnectionType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UserConnection message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ConnectionType {
        [pbr::OriginalName("Nothing")] Nothing = 0,
        [pbr::OriginalName("Connect")] Connect = 1,
        [pbr::OriginalName("TryConnect")] TryConnect = 2,
        [pbr::OriginalName("AcceptConnect")] AcceptConnect = 3,
        [pbr::OriginalName("DisConnect")] DisConnect = 4,
      }

    }
    #endregion

  }

  public sealed partial class GameEvent : pb::IMessage<GameEvent> {
    private static readonly pb::MessageParser<GameEvent> _parser = new pb::MessageParser<GameEvent>(() => new GameEvent());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server2N.GameContentReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent(GameEvent other) : this() {
      act_ = other.act_;
      actionProperty_ = other.actionProperty_;
      eventPositionX_ = other.eventPositionX_;
      eventPositionY_ = other.eventPositionY_;
      velocityX_ = other.velocityX_;
      velocityY_ = other.velocityY_;
      invokerId_ = other.invokerId_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameEvent Clone() {
      return new GameEvent(this);
    }

    /// <summary>Field number for the "act" field.</summary>
    public const int ActFieldNumber = 1;
    private global::Server2N.GameEvent.Types.action act_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.GameEvent.Types.action Act {
      get { return act_; }
      set {
        act_ = value;
      }
    }

    /// <summary>Field number for the "actionProperty" field.</summary>
    public const int ActionPropertyFieldNumber = 5;
    private int actionProperty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActionProperty {
      get { return actionProperty_; }
      set {
        actionProperty_ = value;
      }
    }

    /// <summary>Field number for the "EventPositionX" field.</summary>
    public const int EventPositionXFieldNumber = 6;
    private float eventPositionX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float EventPositionX {
      get { return eventPositionX_; }
      set {
        eventPositionX_ = value;
      }
    }

    /// <summary>Field number for the "EventPositionY" field.</summary>
    public const int EventPositionYFieldNumber = 7;
    private float eventPositionY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float EventPositionY {
      get { return eventPositionY_; }
      set {
        eventPositionY_ = value;
      }
    }

    /// <summary>Field number for the "VelocityX" field.</summary>
    public const int VelocityXFieldNumber = 8;
    private float velocityX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float VelocityX {
      get { return velocityX_; }
      set {
        velocityX_ = value;
      }
    }

    /// <summary>Field number for the "VelocityY" field.</summary>
    public const int VelocityYFieldNumber = 9;
    private float velocityY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float VelocityY {
      get { return velocityY_; }
      set {
        velocityY_ = value;
      }
    }

    /// <summary>Field number for the "invokerId" field.</summary>
    public const int InvokerIdFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_invokerId_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> invokerId_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> InvokerId {
      get { return invokerId_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Act != other.Act) return false;
      if (ActionProperty != other.ActionProperty) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(EventPositionX, other.EventPositionX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(EventPositionY, other.EventPositionY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelocityX, other.VelocityX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VelocityY, other.VelocityY)) return false;
      if(!invokerId_.Equals(other.invokerId_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Act != 0) hash ^= Act.GetHashCode();
      if (ActionProperty != 0) hash ^= ActionProperty.GetHashCode();
      if (EventPositionX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(EventPositionX);
      if (EventPositionY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(EventPositionY);
      if (VelocityX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelocityX);
      if (VelocityY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VelocityY);
      hash ^= invokerId_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Act != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Act);
      }
      if (ActionProperty != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ActionProperty);
      }
      if (EventPositionX != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(EventPositionX);
      }
      if (EventPositionY != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(EventPositionY);
      }
      if (VelocityX != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(VelocityX);
      }
      if (VelocityY != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(VelocityY);
      }
      invokerId_.WriteTo(output, _repeated_invokerId_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Act != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Act);
      }
      if (ActionProperty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActionProperty);
      }
      if (EventPositionX != 0F) {
        size += 1 + 4;
      }
      if (EventPositionY != 0F) {
        size += 1 + 4;
      }
      if (VelocityX != 0F) {
        size += 1 + 4;
      }
      if (VelocityY != 0F) {
        size += 1 + 4;
      }
      size += invokerId_.CalculateSize(_repeated_invokerId_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameEvent other) {
      if (other == null) {
        return;
      }
      if (other.Act != 0) {
        Act = other.Act;
      }
      if (other.ActionProperty != 0) {
        ActionProperty = other.ActionProperty;
      }
      if (other.EventPositionX != 0F) {
        EventPositionX = other.EventPositionX;
      }
      if (other.EventPositionY != 0F) {
        EventPositionY = other.EventPositionY;
      }
      if (other.VelocityX != 0F) {
        VelocityX = other.VelocityX;
      }
      if (other.VelocityY != 0F) {
        VelocityY = other.VelocityY;
      }
      invokerId_.Add(other.invokerId_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            act_ = (global::Server2N.GameEvent.Types.action) input.ReadEnum();
            break;
          }
          case 40: {
            ActionProperty = input.ReadInt32();
            break;
          }
          case 53: {
            EventPositionX = input.ReadFloat();
            break;
          }
          case 61: {
            EventPositionY = input.ReadFloat();
            break;
          }
          case 69: {
            VelocityX = input.ReadFloat();
            break;
          }
          case 77: {
            VelocityY = input.ReadFloat();
            break;
          }
          case 82:
          case 80: {
            invokerId_.AddEntriesFrom(input, _repeated_invokerId_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GameEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum action {
        [pbr::OriginalName("Nothing")] Nothing = 0,
        [pbr::OriginalName("Move")] Move = 100,
        [pbr::OriginalName("Stop")] Stop = 101,
        [pbr::OriginalName("Jump")] Jump = 102,
        [pbr::OriginalName("Shoot")] Shoot = 103,
        [pbr::OriginalName("GetHit")] GetHit = 104,
        [pbr::OriginalName("Spawn")] Spawn = 105,
        [pbr::OriginalName("UserSync")] UserSync = 106,
      }

    }
    #endregion

  }

  public sealed partial class PacketBody : pb::IMessage<PacketBody> {
    private static readonly pb::MessageParser<PacketBody> _parser = new pb::MessageParser<PacketBody>(() => new PacketBody());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PacketBody> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Server2N.GameContentReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketBody() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketBody(PacketBody other) : this() {
      msgType_ = other.msgType_;
      Connect = other.connect_ != null ? other.Connect.Clone() : null;
      Notice = other.notice_ != null ? other.Notice.Clone() : null;
      Event = other.event_ != null ? other.Event.Clone() : null;
      senderId_ = other.senderId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PacketBody Clone() {
      return new PacketBody(this);
    }

    /// <summary>Field number for the "msgType" field.</summary>
    public const int MsgTypeFieldNumber = 10000;
    private global::Server2N.PacketBody.Types.messageType msgType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.PacketBody.Types.messageType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "connect" field.</summary>
    public const int ConnectFieldNumber = 6;
    private global::Server2N.UserConnection connect_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.UserConnection Connect {
      get { return connect_; }
      set {
        connect_ = value;
      }
    }

    /// <summary>Field number for the "notice" field.</summary>
    public const int NoticeFieldNumber = 10001;
    private global::Server2N.GlobalNotice notice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.GlobalNotice Notice {
      get { return notice_; }
      set {
        notice_ = value;
      }
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 7;
    private global::Server2N.GameEvent event_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Server2N.GameEvent Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    /// <summary>Field number for the "senderId" field.</summary>
    public const int SenderIdFieldNumber = 8;
    private int senderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SenderId {
      get { return senderId_; }
      set {
        senderId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PacketBody);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PacketBody other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (!object.Equals(Connect, other.Connect)) return false;
      if (!object.Equals(Notice, other.Notice)) return false;
      if (!object.Equals(Event, other.Event)) return false;
      if (SenderId != other.SenderId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != 0) hash ^= MsgType.GetHashCode();
      if (connect_ != null) hash ^= Connect.GetHashCode();
      if (notice_ != null) hash ^= Notice.GetHashCode();
      if (event_ != null) hash ^= Event.GetHashCode();
      if (SenderId != 0) hash ^= SenderId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (connect_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Connect);
      }
      if (event_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Event);
      }
      if (SenderId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(SenderId);
      }
      if (MsgType != 0) {
        output.WriteRawTag(128, 241, 4);
        output.WriteEnum((int) MsgType);
      }
      if (notice_ != null) {
        output.WriteRawTag(138, 241, 4);
        output.WriteMessage(Notice);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != 0) {
        size += 3 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (connect_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Connect);
      }
      if (notice_ != null) {
        size += 3 + pb::CodedOutputStream.ComputeMessageSize(Notice);
      }
      if (event_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Event);
      }
      if (SenderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SenderId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PacketBody other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != 0) {
        MsgType = other.MsgType;
      }
      if (other.connect_ != null) {
        if (connect_ == null) {
          connect_ = new global::Server2N.UserConnection();
        }
        Connect.MergeFrom(other.Connect);
      }
      if (other.notice_ != null) {
        if (notice_ == null) {
          notice_ = new global::Server2N.GlobalNotice();
        }
        Notice.MergeFrom(other.Notice);
      }
      if (other.event_ != null) {
        if (event_ == null) {
          event_ = new global::Server2N.GameEvent();
        }
        Event.MergeFrom(other.Event);
      }
      if (other.SenderId != 0) {
        SenderId = other.SenderId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 50: {
            if (connect_ == null) {
              connect_ = new global::Server2N.UserConnection();
            }
            input.ReadMessage(connect_);
            break;
          }
          case 58: {
            if (event_ == null) {
              event_ = new global::Server2N.GameEvent();
            }
            input.ReadMessage(event_);
            break;
          }
          case 64: {
            SenderId = input.ReadInt32();
            break;
          }
          case 80000: {
            msgType_ = (global::Server2N.PacketBody.Types.messageType) input.ReadEnum();
            break;
          }
          case 80010: {
            if (notice_ == null) {
              notice_ = new global::Server2N.GlobalNotice();
            }
            input.ReadMessage(notice_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PacketBody message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum messageType {
        [pbr::OriginalName("GameEvent")] GameEvent = 0,
        [pbr::OriginalName("UserConnection")] UserConnection = 10000,
        [pbr::OriginalName("GlobalNotice")] GlobalNotice = 10001,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
